# Generated by Django 6.0.3 on 2026-03-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('objective', models.TextField()),
                ('resume_professional', models.TextField(blank=True, null=True)),
                ('ability', models.TextField(blank=True, null=True)),
                ('curse_certifications', models.TextField(blank=True, null=True)),
                ('Languages', models.CharField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.address')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.phone')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='curriculo.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('stat_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('activities', models.TextField()),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='curriculo.curriculo')),
            ],
        ),
    ]
