# Generated by Django 6.0.3 on 2026-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='Languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='ability',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='curse_certifications',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='objective',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='resume_professional',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
