# Generated by Django 6.0.3 on 2026-03-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_alter_curriculo_languages_alter_curriculo_ability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
