# Generated by Django 6.0.3 on 2026-03-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_alter_curriculo_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculo',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
