# Generated by Django 6.0.3 on 2026-03-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_rename_first_name_curriculo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='curse_certifications',
            field=models.TextField(blank=True, max_length=455, null=True),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='resume_professional',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
